# name: String - Name of node
# cpu: int or float - Number of CPUs
# memory: int - Memory size in Megabyte (smallest node size support 1MB)
# labels: List - List of labels that are attached to the node

resources:
  - name: node-1
    cpu: 0.1
    memory: 100
  - name: node-2
    cpu: 0.3
    memory: 535
  - name: node-3
    cpu: 0.2
    memory: 2048
  - name: node-4
    cpu: 2
    memory: 540
    labels:
      cloud: public
