# name: String - Name of node
# cpu: int or float - Number of CPUs
# memory: int - Memory size in Megabyte (smallest node size support 1MB)
# labels: List - List of labels that are attached to the node

resources:
  - name: node-1
    cpu: 2
    memory: 8192
  - name: node-2
    cpu: 3
    memory: 2048
  - name: node-3
    cpu: 4
    memory: 4096
    labels:
      cloud: public

#    app = [({"vulnerability": 0.8, "memory": 200, "runtime": "java"})];
#        resources = [({"location": "intranet"}), ({"memory": 800, "location": "dmz"})]
#        # dep_rules: deployment rules {a.factor: (f.factor, op, value)} (special value: IDENTITY)
#        dep_rules = {
#             "vulnerability": ("location", "=", "dmz"),
#             "memory": ("memory", ">=", IDENTITY),
#             "runtime": ("runtime", "=", IDENTITY)
#        }